apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: project-1
  source:
    path: application/helm/nginx
    repoURL: https://github.com/BenLazregAhmed/argocd.git
    targetRevision: main