apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: matrix-generator-ex1
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/BenLazregAhmed/argocd.git
              revision: main
              directories:
                - path: applicationset-01/git-generator/ressources/*
          - list:
              elements:
                - environment: pre-staging
                  server: https://kubernetes.default.svc
                - environment: staging
                  server: https://192.168.250.10:5443
  template:
    metadata:
      name: '{{path.basename}}-{{environment}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/BenLazregAhmed/argocd.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: '{{server}}'
        namespace: '{{environment}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true