apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: matrix-generator-ex1
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/BenLazregAhmed/argocd.git
              revision: main
              directories:
                - path: applicationset-01/git-generator/ressources/*
          - clusters: {}
  template:
    metadata:
      name: '{{path.basename}}-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/BenLazregAhmed/argocd.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: '{{server}}'
        namespace: '{{metadata.labels.environment}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true