apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-directory
spec:
  destination:
    namespace: directory
    server: https://kubernetes.default.svc
  project: default
  source:
#    directory:
#      exclude: 'service.yml'
#      include: '{service-account.yml,service.yml}'
#     recurse: true
    path: application/directoryOfManifests
    repoURL: https://github.com/BenLazregAhmed/argocd.git
    targetRevision: main