apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
spec:
  destination:
    namespace: sync-phases-waves
    server: https://kubernetes.default.svc
  project: project-1
  source:
    path: app/sync-phases-waves
    repoURL: https://github.com/BenLazregAhmed/argocd.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true