apiVersion: v1
kind: Secret
metadata:
  name: https-private-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: "git"
  url: "https://github.com/BenLazregAhmed/argo-tuto-private-repo.git"
  username: "argo-private-repo" #token name
  password: ""