apiVersion: v1
kind: Secret
metadata:
  name: https-private-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: "git"
  url: "https://github.com/BenLazregAhmed"
  username: "argo-private-repo" #token name
  password: ""

  # this allows to use any repo that matches this prefix https://github.com/BenLazregAhmed
  # for example https://github.com/BenLazregAhmed/xyz.git , https://github.com/BenLazregAhmed/abc.git ...
  # we can do same for ssh