apiVersion: batch/v1
kind: Job
metadata:
  name: post-sync
  namespace: sync-phases-waves
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
        - name: post-sync
          image: alpine:latest
          command: [ "/bin/sh", "-c" ]
          args: [ "echo 'pre job succeeded'; exit 0" ]
      restartPolicy: Never
  backoffLimit: 4
  