apiVersion: batch/v1
kind: Job
metadata:
  name: health-check-pre-job
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookFailed
  namespace: sync-phases-waves
spec:
  template:
    spec:
      containers:
        - name: health-check
          image: curlimages/curl
          command:
            - sh
            - -c
            - |
              curl -s -o /dev/null -w "%{http_code}" "https://httpbin.org/status/200" | grep -q "200" && exit 0 || exit 1
  backoffLimit: 0