apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate-post # post-promotion-analysis
spec:
  args:
    - name: service-port
      value: "5000" #default value can be override by the value passed in the rollout
    - name: service-namespace
  metrics:
    - name: success-rate-post
      provider:
        job:
          metadata:
            labels:
              analysis: post-promotion # labels defined here will be copied to the Job object
          spec:
            backoffLimit: 0
            template:
              spec:
                containers:
                  - name: success-rate-post
                    image: ahmedevops/app-success-rate # this is the same image that we built to get success_rate . you can find related files (Dockerfile, app-success-rate.sh) in the current directory
                    env:
                      - name: service_url
                        value: "http://rollout-bluegreen-active.{{args.service-namespace}}.svc.cluster.local:{{args.service-port}}"
                    command: ["/bin/bash", "-c"]
                    args:
                      - ./app-success-rate.sh
                restartPolicy: Never