apiVersion: v1
kind: Secret
metadata:
  name: external
  labels:
    argocd.argoproj.io/secret-type: cluster
  namespace: argocd
type: Opaque
stringData:
  name: "ahmedevops"
  server: "https://192.168.250.10:5443"
  config: |
    {
      "bearerToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6ImNocF9Ub2d5dHhTVlJpM3NCVmxiLUtwVDRtTzFLS3ZTMVN5eUZxdVA2Q0EifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJrM3MiXSwiZXhwIjoxNzU1MTUyODYzLCJpYXQiOjE3NTUxNDkyNjMsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiODdjYWQ3NGItM2MzOS00Mzc5LWJiNTItYTVhNTFlNDk0M2MwIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0Iiwic2VydmljZWFjY291bnQiOnsibmFtZSI6Im5ldy1jbHVzdGVyLXNhIiwidWlkIjoiN2M4MDZkZmUtNjBjYS00Zjg2LTkxOWUtNTFkMzMxMzIwZDM5In19LCJuYmYiOjE3NTUxNDkyNjMsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0Om5ldy1jbHVzdGVyLXNhIn0.HvrnCGODQDSnGGpMJ_5RMOoiEjDvdzMfnnqxl_s7-WjRmLUnUc7cK_vUTIqBXmLmwd8jf2joRMKTYgrgbmdyq4jX5Yxgy_Gs-U3JfuDPSzdcrmLWWkleYFu8iamIX505zjyCwHDxMbSDBfowIB1XRvlcWakMG3SXTabAsZdS5dl5CLneVDRax9Hns5ddkKwDuBuDv69oFyn2QQYvOTkUuvjiv-YrD8_01jgpBG6trUGEI7MFPEc8XDJmLKRo338r62Ib0JBFa5pauWkaQG6BAzMohTt_rzlhw1RG5BYSaKTw3IIYOE5dqK8c10vcHscRVpxi0gRsgWoK2vW4425teA",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTlRVd09UTXpNekV3SGhjTk1qVXdPREV6TVRNMU5UTXhXaGNOTXpVd09ERXhNVE0xTlRNeApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTlRVd09UTXpNekV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTYnpNZUt5Q3VDem80T2JPdFJEYVNRS200OWp6d3pBMWFuMkxvZ202Y1QKbkV2N3FIVGpyZkl4aXFOQXlXV3RnL2NSbGtOR1pQekhWWVdnbTFpQzFDcmlvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXgzSkFVcHlPeG1seVpPTjBCaWpwCnBMcWNXcjB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU5qQlV1MDJOVXloYTFQeEo1a3BZdHZ4OU5XQXhWMDIKUmpXd0dVS3dWa3VBQWlBVlI2VmFsRjNDMkFjdzU3NG4vZ2RlYUlPNzEyMHVRS3lMUVBGQnAySmp6dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      }
    }