apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: second-cluster-app
  namespace: argocd
spec:
  destination:
    namespace: external
    server: "https://192.168.250.10:5443"
  project: default
  source:
    path: sync-phases-waves/app
    repoURL: https://github.com/BenLazregAhmed/argocd.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true