apiVersion: v1
kind: Secret
metadata:
  name: local
  labels:
    argocd.argoproj.io/secret-type: cluster
    environment: pre-staging
  namespace: argocd
type: Opaque
stringData:
  name: "local"
  server: "https://kubernetes.default.svc"
  config: |
    {
      "tlsClientConfig": {
        "insecure": false
      }
    }