apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: git-directories-generator-ex2
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/devopshobbies/argocd-tutorial.git
        revision: main
        directories:
          - path: applicationset-01/git-generator/ressources/*
          - path: applicationset-01/git-generator/ressources/nginx-manifests
            exclude: true
  template:
    metadata:
      name: '{{path.basename}}-application'
    spec:
      project: default
      source:
        repoURL: https://github.com/BenLazregAhmed/argocd.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}-ns'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true