apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: git-files-generator-ex1
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/BenLazregAhmed/argocd.git
        revision: main
        files:
          - path: applicationset-01/git-generator/cluster-config/**/config.json
  template:
    metadata:
      name: '{{cluster.name}}-application'
    spec:
      project: default
      source:
        repoURL: https://github.com/BenLazregAhmed/argocd.git
        targetRevision: main
        path: '{{cluster.path}}'
      destination:
        server: '{{cluster.address}}'
        namespace: '{{cluster.namespace}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true